#!/usr/bin/env python3
"""Draw the brand mirror mark as the desktop and Android launcher icons.

The mark is one piece of geometry: a rounded upright frame, a diagonal
reflection stroke and three pixels along the bottom, on a 100x100 design
square. It is drawn here in Pillow rather than rendered by the render core, so
the icons build on a machine with nothing but Python and Pillow installed, and
no raster blob (and no stale 64x64 mirror layout) has to be committed. Every
size is drawn at 4x and downsampled with Lanczos, which is what keeps the
graduated strokes clean at 48px without a native drawing dependency.

The same geometry, unit for unit, is what designer/lib/src/ui/app_brand.dart
paints inside the app (MirrorMark), so the launcher icon and the in-app mark
are one drawing at two scales. Keep the constants below and that painter in
step.

Outputs, under designer/android/app/src/main/res/:
    mipmap-*/ic_launcher.png                   legacy icon, API < 26
    mipmap-*/ic_launcher_foreground.png        adaptive foreground, API 26+,
                                               reused as the Android 12 splash
                                               icon so the two can never drift
    mipmap-anydpi-v26/ic_launcher.xml          adaptive icon definition
    values/brand_colours.xml                   the brand ink, shared by the
                                               adaptive background, the splash
                                               and the window behind Flutter
    drawable/launch_background.xml             launch window, API < 21
    drawable-v21/launch_background.xml         launch window, API 21-30
    values/styles.xml                          light launch and window themes
    values-night/styles.xml                    ... and the night ones
    values-v31/styles.xml                      Android 12+ splash screen
    values-night-v31/styles.xml                ... and the night one

Four styles files rather than two because night mode outranks the API level
when the platform picks a resource, so an Android 12 night device reads
values-night-v31 and would otherwise miss the splash attributes entirely.

With --linux-dir, into a hicolor icon theme:
    <size>x<size>/apps/mirror-designer.png     the sizes a desktop asks for

Usage:
    python3 designer/tool/gen_icon.py                       # the Android set
    python3 designer/tool/gen_icon.py --linux-dir "$HOME/.local/share/icons/hicolor"
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    from PIL import Image, ImageDraw
except ImportError:
    sys.exit("Pillow is required to generate the icons (python3 -m pip install Pillow)")

DESIGNER = Path(__file__).resolve().parent.parent
RES = DESIGNER / "android" / "app" / "src" / "main" / "res"

# Drawn at this multiple and downsampled, which is the whole anti-aliasing
# story: Pillow has no native rasteriser worth using here.
SUPERSAMPLE = 4

# ------------------------------------------------------------ mark geometry
# Design square, 100x100, matching _MirrorMarkPainter in app_brand.dart. The
# frame is stroked on its path centre there, which is what the half-stroke
# offset in _draw_mark reproduces.
FRAME = (24.0, 14.0, 52.0, 72.0)            # x, y, width, height
FRAME_RADIUS = 12.0
REFLECTION = ((38.0, 56.0), (60.0, 34.0))   # diagonal stroke, round caps
PIXELS = ((39.0, 72.0), (50.0, 72.0), (61.0, 72.0))
PIXEL_RADIUS = 2.0
STROKE = 5.0

MINT = (0x83, 0xE1, 0xC5, 255)      # scheme.primary
PALE = (0xE6, 0xF0, 0xED, 255)      # scheme.onSurface, the reflection
INK = (0x0B, 0x14, 0x18, 255)       # scheme.surface, the backdrop

# Scale factor relative to mdpi for each Android density bucket.
DENSITIES = {
    "mdpi": 1,
    "hdpi": 1.5,
    "xhdpi": 2,
    "xxhdpi": 3,
    "xxxhdpi": 4,
}

LEGACY_BASE = 48        # px at mdpi for the legacy square icon
LEGACY_MARK = 0.92      # mark design square, as a fraction of that icon: the
                        # frame then fills two thirds of the plate, the margin
                        # a pre-26 launcher expects baked into the bitmap
FG_CANVAS_BASE = 108    # px at mdpi for the adaptive foreground canvas
FG_MARK = 64 / 108      # mark design square inside it, so the frame's 72-unit
                        # height lands at 46dp, inside the launcher's 66dp
                        # adaptive-icon safe circle
BACKDROP_RADIUS = 0.22  # corner radius of the rounded ink plate, as a fraction

LINUX_SIZES = (64, 128, 256, 512)

ADAPTIVE_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/gen_icon.py from the mark's geometry. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/brand_background"/>
    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>
</adaptive-icon>
"""

COLOURS_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/gen_icon.py. One ink for everything the platform paints
     before Flutter draws: the adaptive icon's background, the splash screen and
     the window. The app is dark in either system theme, so none of them may
     fall back to the platform's white. -->
<resources>
    <color name="brand_background">#0B1418</color>
</resources>
"""

LAUNCH_BACKGROUND_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/gen_icon.py. The window behind the process while it
     starts: the brand ink and the mark, never the stock white. The mark is the
     adaptive foreground, which already carries the safe-zone margin. -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/brand_background" />
    <item>
        <bitmap
            android:gravity="center"
            android:src="@mipmap/ic_launcher_foreground" />
    </item>
</layer-list>
"""


def styles_xml(android_12: bool) -> str:
    """The launch and window themes, with the splash screen attributes on API 31+.

    Android 12 draws its own splash screen before the window appears, from the
    windowSplashScreen attributes; left unset it paints the app icon on a
    background derived from the theme, which is the stock white flash. The two
    themes stay parented on the black platform theme because the app is dark
    whatever the system theme is, and ?android:colorBackground is white in
    light mode.
    """
    launch = [
        '        <item name="android:windowBackground">@drawable/launch_background</item>',
    ]
    if android_12:
        launch += [
            "        <!-- Android 12+ splash screen, drawn before this window exists. -->",
            '        <item name="android:windowSplashScreenBackground">@color/brand_background</item>',
            '        <item name="android:windowSplashScreenAnimatedIcon">@mipmap/ic_launcher_foreground</item>',
        ]
    launch_items = "\n".join(launch)
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/gen_icon.py. -->
<resources>
    <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
{launch_items}
    </style>
    <style name="NormalTheme" parent="@android:style/Theme.Black.NoTitleBar">
        <item name="android:windowBackground">@color/brand_background</item>
    </style>
</resources>
"""


def _draw_mark(draw: ImageDraw.ImageDraw, canvas: int, mark_ratio: float) -> None:
    """Draw the mark centred on a canvas, its design square `mark_ratio` wide."""
    extent = canvas * mark_ratio
    origin = (canvas - extent) / 2
    unit = extent / 100

    stroke = max(1, round(STROKE * unit))
    half = stroke / 2

    def at(*values: float) -> list[float]:
        return [origin + value * unit for value in values]

    x, y, width, height = FRAME
    # Pillow strokes inside the box it is given, Flutter around the path, so the
    # box grows by half a stroke and the radius with it.
    left, top, right, bottom = at(x, y, x + width, y + height)
    draw.rounded_rectangle(
        (left - half, top - half, right + half, bottom + half),
        radius=round(FRAME_RADIUS * unit) + half,
        outline=MINT,
        width=stroke,
    )
    start, end = REFLECTION
    draw.line((*at(*start), *at(*end)), fill=PALE, width=stroke)
    for point in REFLECTION:
        cap = at(*point)
        draw.ellipse(
            (cap[0] - half, cap[1] - half, cap[0] + half, cap[1] + half), fill=PALE
        )
    for point in PIXELS:
        centre = at(*point)
        radius = PIXEL_RADIUS * unit
        draw.ellipse(
            (centre[0] - radius, centre[1] - radius, centre[0] + radius, centre[1] + radius),
            fill=MINT,
        )


def render(size: int, mark_ratio: float, backdrop_radius: float | None) -> Image.Image:
    """One icon: the mark alone, or the mark on a rounded ink plate."""
    canvas = size * SUPERSAMPLE
    image = Image.new("RGBA", (canvas, canvas), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    if backdrop_radius is not None:
        draw.rounded_rectangle(
            (0, 0, canvas - 1, canvas - 1),
            radius=round(canvas * backdrop_radius),
            fill=INK,
        )
    _draw_mark(draw, canvas, mark_ratio)
    return image.resize((size, size), Image.Resampling.LANCZOS)


def save(image: Image.Image, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path)
    print(f"{path.relative_to(RES)} ({image.width}x{image.height})")


def gen_android() -> None:
    """Write everything the Android launcher and the splash screen need."""
    for bucket, scale in DENSITIES.items():
        legacy = round(LEGACY_BASE * scale)
        save(
            render(legacy, LEGACY_MARK, BACKDROP_RADIUS),
            RES / f"mipmap-{bucket}" / "ic_launcher.png",
        )

        canvas = round(FG_CANVAS_BASE * scale)
        save(
            render(canvas, FG_MARK, None),
            RES / f"mipmap-{bucket}" / "ic_launcher_foreground.png",
        )

    # The adaptive icon draws its background from the colour resource, so the
    # foreground keeps the alpha it needs to sit on any launcher shape.
    for path, text in (
        (RES / "mipmap-anydpi-v26" / "ic_launcher.xml", ADAPTIVE_XML),
        (RES / "values" / "brand_colours.xml", COLOURS_XML),
        (RES / "drawable" / "launch_background.xml", LAUNCH_BACKGROUND_XML),
        (RES / "drawable-v21" / "launch_background.xml", LAUNCH_BACKGROUND_XML),
        (RES / "values" / "styles.xml", styles_xml(android_12=False)),
        (RES / "values-night" / "styles.xml", styles_xml(android_12=False)),
        (RES / "values-v31" / "styles.xml", styles_xml(android_12=True)),
        (RES / "values-night-v31" / "styles.xml", styles_xml(android_12=True)),
    ):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print(path.relative_to(RES))

    # The old generator put the adaptive background in its own file. Drop it if
    # a tree generated before this one still carries it.
    stale = RES / "values" / "ic_launcher_background.xml"
    if stale.exists():
        stale.unlink()
        print(f"removed {stale.relative_to(RES)} (superseded by values/brand_colours.xml)")


def gen_linux(root: Path) -> None:
    """Write the desktop icons into a hicolor theme root."""
    for size in LINUX_SIZES:
        image = render(size, LEGACY_MARK, BACKDROP_RADIUS)
        out = root / f"{size}x{size}" / "apps" / "mirror-designer.png"
        out.parent.mkdir(parents=True, exist_ok=True)
        image.save(out)
        print(f"{out} ({size}x{size})")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--android",
        action="store_true",
        help="write the Android resources (the default when nothing else is asked for)",
    )
    parser.add_argument(
        "--linux-dir",
        metavar="DIR",
        help="write the desktop icons into this hicolor theme root, e.g. "
        "~/.local/share/icons/hicolor",
    )
    args = parser.parse_args()

    if args.linux_dir:
        gen_linux(Path(args.linux_dir).expanduser())

    if args.android or not args.linux_dir:
        if not RES.is_dir():
            sys.exit(f"no Android resources at {RES}; run designer/setup.sh first")
        gen_android()

    print("done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
