#!/usr/bin/env python3
"""Generate the Android launcher icons from the render core.

The app icon lives as a mirror layout, designer/assets/icon.json, rendered by
the same C core the panel runs, so the icon is the panel's own output rather
than a hand-drawn raster kept in step by hand.

The whole android/ tree is generated by setup.sh and gitignored, so this script
writes everything the launcher needs, PNGs and the two adaptive-icon XML files,
from the one committed layout.

Android launcher icons ship as PNGs at fixed densities that are not integer
multiples of the 64x64 canvas, so a 1024px master is rendered once and
resampled with Lanczos. That is the one place the repository deliberately
resamples: the icon's display face is anti-aliased (not the hard 5x7 pixel
glyphs the Linux icon renders per size), so Lanczos keeps it crisp.

Outputs, under android/app/src/main/res/:
    mipmap-*/ic_launcher.png            legacy square icon (API < 26)
    mipmap-*/ic_launcher_foreground.png adaptive foreground (API 26+)
    mipmap-anydpi-v26/ic_launcher.xml   adaptive icon definition
    values/ic_launcher_background.xml   adaptive background colour

Usage:
    python3 designer/tool/gen_icon.py
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required to generate the icons (python3 -m pip install Pillow)")

DESIGNER = Path(__file__).resolve().parent.parent
REPO = DESIGNER.parent
ICON_LAYOUT = DESIGNER / "assets" / "icon.json"
CLI = REPO / "core" / "build" / "host" / "mirror-cli"
RES = DESIGNER / "android" / "app" / "src" / "main" / "res"

# Scale factor relative to mdpi for each density bucket.
DENSITIES = {
    "mdpi": 1,
    "hdpi": 1.5,
    "xhdpi": 2,
    "xxhdpi": 3,
    "xxxhdpi": 4,
}

LEGACY_BASE = 48      # px at mdpi for the square legacy icon
FG_CANVAS_BASE = 108  # px at mdpi for the adaptive foreground canvas
FG_MARK_BASE = 64     # px at mdpi for the mark centred inside the foreground

# The adaptive background matches the layout's black canvas, so the foreground
# mark's own background blends into the launcher mask seamlessly.
BACKGROUND_COLOUR = "#000000"

ADAPTIVE_XML = """<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background"/>
    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>
</adaptive-icon>
"""

BACKGROUND_XML = """<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">%s</color>
</resources>
"""


def build_cli() -> Path:
    """Return the mirror-cli path, building it if it is missing."""
    if not CLI.exists():
        subprocess.run(
            ["make", "-C", str(REPO / "core"), "-f", "Makefile.host"],
            check=True,
            capture_output=True,
        )
    if not CLI.exists():
        sys.exit(f"could not build {CLI}")
    return CLI


def render_master(cli: Path) -> Image.Image:
    """Render the layout once at 1024px (16x the 64x64 canvas)."""
    tmp = Path(tempfile.mkdtemp(prefix="mirror-icon-"))
    out = tmp / "icon-master.png"
    subprocess.run(
        [str(cli), str(ICON_LAYOUT), "-m", "typical", "-s", "16", "-o", str(out)],
        check=True,
        capture_output=True,
    )
    return Image.open(out).convert("RGBA")


def resample(src: Image.Image, size: int) -> Image.Image:
    return src.resize((size, size), Image.Resampling.LANCZOS)


def gen_legacy(master: Image.Image) -> None:
    for bucket, scale in DENSITIES.items():
        size = round(LEGACY_BASE * scale)
        out = RES / f"mipmap-{bucket}" / "ic_launcher.png"
        out.parent.mkdir(parents=True, exist_ok=True)
        resample(master, size).convert("RGB").save(out)
        print(f"{out.relative_to(RES)} ({size}x{size})")


def gen_foreground(master: Image.Image) -> None:
    for bucket, scale in DENSITIES.items():
        canvas = round(FG_CANVAS_BASE * scale)
        mark = round(FG_MARK_BASE * scale)
        fg = Image.new("RGBA", (canvas, canvas), (0, 0, 0, 0))
        icon = resample(master, mark)
        origin = (canvas - mark) // 2
        fg.paste(icon, (origin, origin))
        out = RES / f"mipmap-{bucket}" / "ic_launcher_foreground.png"
        out.parent.mkdir(parents=True, exist_ok=True)
        fg.save(out)
        print(f"{out.relative_to(RES)} ({canvas}x{canvas})")


def write_adaptive_xml() -> None:
    out = RES / "mipmap-anydpi-v26" / "ic_launcher.xml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(ADAPTIVE_XML)
    print(f"{out.relative_to(RES)}")

    colour = RES / "values" / "ic_launcher_background.xml"
    colour.parent.mkdir(parents=True, exist_ok=True)
    colour.write_text(BACKGROUND_XML % BACKGROUND_COLOUR)
    print(f"{colour.relative_to(RES)}")


def main() -> int:
    master = render_master(build_cli())
    gen_legacy(master)
    gen_foreground(master)
    write_adaptive_xml()
    print("done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
