/// The smart mirror render core, compiled natively, with the game simulation's
/// Dart face over it.
///
/// Depending on this package makes Flutter compile `core/` and `gamekit/` for
/// the target platform and bundle the resulting shared library, which is what
/// lets `DynamicLibrary.open('libmirror_core_ffi.so')` succeed at runtime.
///
/// It carries two things: the library's own name (below), so the app and the
/// CMake target have one place to disagree loudly rather than silently, and the
/// game simulation and its FFI bindings, which have two consumers - the
/// designer's Games screen and the Jumpman level editor. The layout side of the
/// same library stays in the designer, where it has one consumer.
///
/// The bindings are hand written rather than generated by ffigen: the C surface
/// is about thirty functions that change rarely, and hand written bindings can
/// carry the ownership rules (which returned pointers are borrowed, and how
/// long they stay valid) that a generator would drop.
library mirror_core_ffi;

export 'src/game_engine.dart';
export 'src/game_bindings.dart' show GameLibraryException;

/// Name of the shared library this package produces, without the platform
/// prefix or extension. Kept here so the app and the CMake target have one
/// place to disagree loudly rather than silently.
const String kMirrorCoreLibraryName = 'mirror_core_ffi';
