#!/usr/bin/env bash
#
# Scaffolds the platform-specific build files for the designer.
#
# Flutter's per-platform boilerplate (gradle files, podspecs, runner CMake) is
# version specific, so it is generated with the Flutter you have installed
# rather than checked into the repository. Everything that is actually ours
# (lib/, pubspec.yaml, the plugin's src/CMakeLists.txt) is committed and is
# never touched by this script.
#
# Safe to re-run. It only fills in what is missing.
#
# Usage:
#   ./setup.sh                      # linux and android
#   ./setup.sh linux,android,macos  # pick your own

set -euo pipefail

cd "$(dirname "$0")"
DESIGNER_DIR="$(pwd)"
REPO_ROOT="$(cd .. && pwd)"

PLATFORMS="${1:-linux,android}"

info() { printf '\033[36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[33mwarning:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- toolchain

command -v flutter >/dev/null 2>&1 || die "flutter is not on PATH.

Install it, then re-run this script:
  https://docs.flutter.dev/get-started/install/linux

On Fedora you will also want the desktop build dependencies:
  sudo dnf install clang cmake ninja-build gtk3-devel pkgconf-pkg-config"

info "Flutter: $(flutter --version 2>/dev/null | head -1)"

# The render core is compiled in place rather than vendored, so the repository
# layout has to be intact.
[ -f "$REPO_ROOT/core/ffi/mirror_ffi.c" ] \
  || die "cannot find core/ffi/mirror_ffi.c. Run this from inside the repository."

if [ ! -f "$REPO_ROOT/core/src/fonts/font_registry.c" ]; then
  info "Generating font tables"
  (cd "$REPO_ROOT" && python3 tools/fontgen.py)
fi

# ------------------------------------------------------- platform scaffolding

# Generates a throwaway project and lifts only its platform directories, so a
# regenerate can never clobber hand-written Dart or pubspec entries.
scaffold() {
  local target_dir="$1" template="$2" project_name="$3"
  local tmp created=0

  tmp="$(mktemp -d)"
  # shellcheck disable=SC2064
  trap "rm -rf '$tmp'" RETURN

  local args=(create --platforms="$PLATFORMS" --project-name "$project_name")
  [ -n "$template" ] && args+=(--template="$template")

  flutter "${args[@]}" "$tmp/scaffold" >/dev/null

  for platform in android ios linux macos windows; do
    if [ -d "$tmp/scaffold/$platform" ] && [ ! -d "$target_dir/$platform" ]; then
      cp -r "$tmp/scaffold/$platform" "$target_dir/$platform"
      info "  added $(basename "$target_dir")/$platform"
      created=1
    fi
  done

  [ "$created" -eq 0 ] && info "  $(basename "$target_dir") platform files already present"
  return 0
}

info "Scaffolding the native plugin (compiles core/)"
scaffold "$DESIGNER_DIR/packages/mirror_core_ffi" "plugin_ffi" "mirror_core_ffi"

info "Scaffolding the app"
scaffold "$DESIGNER_DIR" "" "mirror_designer"

# "Save As" uses ACTION_CREATE_DOCUMENT because file_selector has no save
# support on Android. MainActivity.kt is ours; install it over the stub that
# `flutter create` generated (and regenerates) so the fix survives a fresh
# checkout. Guarded so `./setup.sh linux` without android is still safe.
if [ -d "$DESIGNER_DIR/android" ]; then
  cp "$DESIGNER_DIR/tool/MainActivity.kt" \
     "$DESIGNER_DIR/android/app/src/main/kotlin/com/example/mirror_designer/MainActivity.kt"
fi

# AndroidManifest.xml is generated by `flutter create`, so the location
# permission has to be fixed here rather than committed. The generated line
# caps ACCESS_FINE_LOCATION at API 30, which is right for the Bluetooth-scan
# gate but wrong for the setup wizard's "Use my location" button: reading this
# device's own position needs the grant on every API level. Idempotent: the
# capped line is only present until it is replaced once.
manifest="$DESIGNER_DIR/android/app/src/main/AndroidManifest.xml"
if [ -f "$manifest" ]; then
  changed=$(python3 - "$manifest" <<'PY'
import re, sys

path = sys.argv[1]
with open(path) as fh:
    text = fh.read()

capped = re.compile(
    r'^[ \t]*<uses-permission '
    r'android:name="android\.permission\.ACCESS_FINE_LOCATION"'
    r'[^>]*maxSdkVersion[^>]*/>[ \t]*\n',
    re.M)

block = (
    '    <!-- Bluetooth scanning needs the location grant on API <= 30 (the app is\n'
    '         built with neverForLocation on 31+, so nothing else does); the setup\n'
    "         wizard's \"Use my location\" button needs it on every API level to read\n"
    "         this device's own position. Only requested when the owner taps it. -->\n"
    '    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>\n'
    '    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>\n'
)

new = capped.sub(block, text, count=1)
if new != text:
    with open(path, 'w') as fh:
        fh.write(new)
    print('changed')
PY
)
  if [ -n "$changed" ]; then
    info "  uncapped the location permission in $(basename "$manifest")"
  fi
fi

# iOS and macOS refuse to hand out a position when the usage string is
# missing, and their Info.plist is generated by `flutter create` (so it is not
# ours to commit). Insert the key only when it is absent, so a hand-edited
# value is never overwritten.
for plist in "$DESIGNER_DIR/ios/Runner/Info.plist" \
             "$DESIGNER_DIR/macos/Runner/Info.plist"; do
  [ -f "$plist" ] || continue
  python3 - "$plist" <<'PY'
import plistlib, sys
path = sys.argv[1]
with open(path, 'rb') as fh:
    data = plistlib.load(fh)
if 'NSLocationWhenInUseUsageDescription' not in data:
    data['NSLocationWhenInUseUsageDescription'] = (
        'Used once, when you tap "Use my location" while setting up a mirror, '
        'to fill in the mirror\'s coordinates.')
    with open(path, 'wb') as fh:
        plistlib.dump(data, fh)
PY
done

# Every Android build must bundle the firmware the working tree describes, not
# whatever copy was staged by hand last. tool/firmware_bundle.gradle registers
# a gradle task that rebuilds and restages the image before Flutter packs
# assets, so the apply line below is what makes the guarantee hold; the script
# it applies is committed, only this one-line wiring lives in the generated
# scaffolding.
for gradle_file in "$DESIGNER_DIR/android/app/build.gradle.kts" \
                   "$DESIGNER_DIR/android/app/build.gradle"; do
  if [ -f "$gradle_file" ] && ! grep -q firmware_bundle "$gradle_file"; then
    case "$gradle_file" in
      *.kts)
        printf '\n// Installed by setup.sh: bundle the current firmware into every build.\napply(from = "$rootDir/../tool/firmware_bundle.gradle")\n' >> "$gradle_file"
        ;;
      *)
        printf '\n// Installed by setup.sh: bundle the current firmware into every build.\napply from: file("$rootDir/../tool/firmware_bundle.gradle")\n' >> "$gradle_file"
        ;;
    esac
    info "  wired firmware_bundle.gradle into $(basename "$gradle_file")"
  fi
done

# The generated plugin ships a placeholder .c and matching Dart bindings that
# reference functions our core does not have. Left in place they break the
# build, so remove them; src/CMakeLists.txt is ours and points at core/.
rm -f "$DESIGNER_DIR/packages/mirror_core_ffi/src/mirror_core_ffi.c" \
      "$DESIGNER_DIR/packages/mirror_core_ffi/src/mirror_core_ffi.h" \
      "$DESIGNER_DIR/packages/mirror_core_ffi/lib/mirror_core_ffi_bindings_generated.dart" \
      "$DESIGNER_DIR/packages/mirror_core_ffi/ffigen.yaml"

# -------------------------------------------------------------------- icons

# Android launcher icons are rendered from the committed icon layout rather
# than shipped as blobs, so generate them once the Android scaffolding exists.
if [ -d "$DESIGNER_DIR/android/app/src/main/res" ]; then
  info "Generating launcher icons"
  if ! python3 "$DESIGNER_DIR/tool/gen_icon.py"; then
    warn "icon generation failed; the stock launcher icon is left in place"
  fi
fi

# ------------------------------------------------------------------- assets

# Stock layouts are shared with the firmware and the CLI. Linked rather than
# copied so there is exactly one copy of each layout in the repository.
mkdir -p "$DESIGNER_DIR/assets"
if [ ! -e "$DESIGNER_DIR/assets/layouts" ]; then
  ln -s ../../layouts "$DESIGNER_DIR/assets/layouts"
  info "Linked assets/layouts -> layouts/"
fi

info "Fetching packages"
flutter pub get

cat <<EOF

Done. To run:

  cd designer
  flutter run -d linux          # desktop
  flutter run -d <device-id>    # phone, see: flutter devices

If the app opens on "The render engine did not load", the native library was
not built. Check that packages/mirror_core_ffi/<platform>/ exists and re-run
this script.
EOF
