/// This package exists for its native build, not for its Dart API.
///
/// Depending on it makes Flutter compile `core/` for the target platform and
/// bundle the resulting shared library, which is what lets
/// `DynamicLibrary.open('libmirror_core_ffi.so')` succeed at runtime.
///
/// The actual bindings live in the app, at `designer/lib/src/engine/`. They
/// are hand written rather than generated by ffigen: the C surface is about
/// thirty functions that change rarely, and hand written bindings can carry
/// the ownership rules (which returned pointers are borrowed, and how long
/// they stay valid) that a generator would drop.
library mirror_core_ffi;

/// Name of the shared library this package produces, without the platform
/// prefix or extension. Kept here so the app and the CMake target have one
/// place to disagree loudly rather than silently.
const String kMirrorCoreLibraryName = 'mirror_core_ffi';
